### ISSUE TITLE
Lion Ping Reaction Blocked

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#474]
```
Jun 10 18:14:51 SandboxHost-637587683188494289 default error Reaction blocked 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error     DiscordAPIError: Reaction blocked 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at RequestHandler.execute (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:154:13) 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at runMicrotasks (<anonymous>) 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at processTicksAndRejections (node:internal/process/task_queues:93:5) 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at async RequestHandler.push (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:39:14) 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at async LionPingHandler.execute (/usr/src/lion/dist/app/handlers/lionping.handler.js:29:13) 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error         at async /usr/src/lion/dist/app/listener.js:110:17 { 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       method: 'put', 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       path: '/channels/848347794837209118/messages/852717487329509437/reactions/lion:842463877366808606/@me', 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       code: 90001, 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       httpStatus: 403, 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       level: 'error', 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       timestamp: '2021-06-11T01:14:40.895Z', 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       [Symbol(level)]: 'error', 
Jun 10 18:14:51 SandboxHost-637587683188494289 default error       [Symbol(message)]: '{"name":"DiscordAPIError","message":"Reaction blocked","method":"put","path":"/channels/848347794837209118/messages/852717487329509437/reactions/lion:842463877366808606/@me","code":90001,"httpStatus":403,"level":"error","timestamp":"2021-06-11T01:14:40.895Z"}' 
```
![image](https://user-images.githubusercontent.com/39809146/121618086-ce640d00-ca2b-11eb-917e-6d330ad3e1a1.png)

**Comment by tanndlin** [comment]
It's caused by someone blocking Lion 😂😂
Just needs a simple catch

**Comment by suneettipirneni** [comment]
Closing issue due to user anomaly.

**Comment by suneettipirneni** [comment]
we didn't have to close this, I was joking

**Comment by tanndlin** [comment]
Kind of useless to make a change, if we make a change here, we might as well catch *every* react
But its not a crashing issue
