### ISSUE TITLE
Lots of error's when GitHub Bot posts a message

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#496]
This is a very special case, and just may need to be handled as an edge case since this is the only bot that messages in our server other than Lion.
This is a result of this [commit](https://github.com/cs-discord-at-ucf/lion/commit/d44c34a3b672002e8e0ffe37ce3e418b635d1f54), but this change was necessary for #488

```
Jun 21 17:02:58 SandboxHost-637598045098838096 default error While attempting to look up GitHub#0000 as a GuildMember. Unknown User 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error     { 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       name: 'DiscordAPIError', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       message: 'While attempting to look up GitHub#0000 as a GuildMember. Unknown User', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       method: 'get', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       path: '/guilds/384834085752930305/members/578780404342063105', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       code: 10013, 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       httpStatus: 404, 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       level: 'error', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       stack: 'DiscordAPIError: Unknown User\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at RequestHandler.execute (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:154:13)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at runMicrotasks (<anonymous>)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at processTicksAndRejections (node:internal/process/task_queues:93:5)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at async RequestHandler.push (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:39:14)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at async Listener._tryEnsureMessageMember (/usr/src/lion/dist/app/listener.js:73:28)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at async Listener._handleMessageOrMessageUpdate (/usr/src/lion/dist/app/listener.js:52:13)\n' + 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         '    at async ClientService.<anonymous> (/usr/src/lion/dist/app/listener.js:32:13)', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       timestamp: '2021-06-22T00:02:51.231Z', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       [Symbol(level)]: 'error', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error       [Symbol(splat)]: [ 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         DiscordAPIError: Unknown User 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at RequestHandler.execute (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:154:13) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at runMicrotasks (<anonymous>) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at processTicksAndRejections (node:internal/process/task_queues:93:5) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at async RequestHandler.push (/usr/src/lion/node_modules/discord.js/src/rest/RequestHandler.js:39:14) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at async Listener._tryEnsureMessageMember (/usr/src/lion/dist/app/listener.js:73:28) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at async Listener._handleMessageOrMessageUpdate (/usr/src/lion/dist/app/listener.js:52:13) 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error             at async ClientService.<anonymous> (/usr/src/lion/dist/app/listener.js:32:13) { 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error           method: 'get', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error           path: '/guilds/384834085752930305/members/578780404342063105', 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error           code: 10013, 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error           httpStatus: 404 
Jun 21 17:02:58 SandboxHost-637598045098838096 default error         } 
```

**Comment by c650** [comment]
if its a bot we should ignre completely

**Comment by tanndlin** [comment]
> if its a bot we should ignre completely

I had to make that commit for the new automated testing

**Comment by c650** [comment]
> > if its a bot we should ignre completely
> 
> I had to make that commit for the new automated testing

?

**Comment by tanndlin** [comment]
> > > if its a bot we should ignre completely
> 
> > 
> 
> > I had to make that commit for the new automated testing
> 
> 
> 
> ?

That commit should've been in the PR for automated testing, but I made the commit onto Develop when I thought it was gonna be in a separate repo.
